# Bigram Probability Analysis

In [1]:
import pandas as pd
import sys
import os 

sys.path.append(os.path.abspath("../.."))

from scripts import prob

In [2]:
df = pd.read_csv("/Users/senko/Desktop/castro/data/processed/micro_bigram.csv")

df_clean = pd.read_csv("/Users/senko/Desktop/castro/data/processed/clean_bigram.csv")

df_all = pd.read_csv("/Users/senko/Desktop/castro/data/processed/all_bigram.csv")

# Micro Level
## Castro Residents

In [3]:
# Castro_res participants with response_site1=castro and response_site2=marina
prob.forward_prob(df, target_fieldsite="castro_res", target_r1_site="castro", target_r2_site="marina", count_filter=0)
prob.backward_prob(df, target_fieldsite="castro_res", target_r1_site="castro", target_r2_site="marina", count_filter=0)

# Castro_res participants with response_site1=castro and response_site2=mission
prob.forward_prob(df, target_fieldsite="castro_res", target_r1_site="castro", target_r2_site="mission", count_filter=0)
prob.backward_prob(df, target_fieldsite="castro_res", target_r1_site="castro", target_r2_site="mission", count_filter=0)

Forward probability of response2 given response1 for castro_res participants with response_site1=castro and response_site2=marina:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro        boring         marina      1
1            bad         castro           bad         marina      1
2         boring         castro        boring         marina      1
3         change         castro         other         marina      1
5      community         castro           bad         marina      1
6      community         castro       chaotic         marina      1
8      community         castro     normative         marina      1
9      community         castro         other         marina      1
4      community         castro      antitask         marina      2
7      community         castro     geography         marina      2
10     community         castro         young         marina      2
14       diverse         castro         other         marina      1
11       diverse         castro      antitask         marina      2
13       diverse         castro     normative         marina      2
12       diverse         castro    gentrified         marina      3
16           fun         castro           bad         marina      1
17           fun         castro        boring         marina      1
19           fun         castro  institutions         marina      1
20           fun         castro          nice         marina      1
23           fun         castro        sexual         marina      1
24           fun         castro       special         marina      1
21           fun         castro     normative         marina      2
22           fun         castro         other         marina      2
18           fun         castro    gentrified         marina      6
15           fun         castro      antitask         marina      9
25           gay         castro        boring         marina      1
27           gay         castro        gritty         marina      1
29           gay         castro         other         marina      1
30           gay         castro         young         marina      2
26           gay         castro    gentrified         marina      4
28           gay         castro     normative         marina      4
31  institutions         castro      antitask         marina      1
33          nice         castro           bad         marina      1
34          nice         castro        boring         marina      1
35          nice         castro           fun         marina      1
36          nice         castro    gentrified         marina      1
37          nice         castro          nice         marina      1
38          nice         castro     normative         marina      1
39          nice         castro         other         marina      1
32          nice         castro      antitask         marina      2
40     normative         castro        boring         marina      1
41          open         castro          nice         marina      1
43         other         castro    gentrified         marina      1
44         other         castro     normative         marina      1
42         other         castro        boring         marina      2
45       special         castro      antitask         marina      1
47       special         castro          nice         marina      1
46       special         castro    gentrified         marina      2

    probability
0      1.000000
1      1.000000
2      1.000000
3      1.000000
5      0.100000
6      0.100000
8      0.100000
9      0.100000
4      0.200000
7      0.200000
10     0.200000
14     0.125000
11     0.250000
13     0.250000
12     0.375000
16     0.040000
17     0.040000
19     0.040000
20     0.040000
23     0.040000
24     0.040000
21     0.080000
22     0.080000
18     0.240000
15     0.360000
25     0.076923
27     0.076923
29     0.076923
30     0.153846
26     0.307692
28     0.307692
31     1.000000
33     0.111111
34     0.111111
35     0.111111
36     0.111111
37     0.111111
38     0.111111
39     0.111111
32     0.222222
40     1.000000
41     1.000000
43     0.250000
44     0.250000
42     0.500000
45     0.250000
47     0.250000
46     0.500000
Backward probability of response1 given response2 for castro_res participants with response_site1=castro and response_site2=marina:
       category1 response_site1     category2 response_site2  count  \
31  institutions         castro      antitask         marina      1
45       special         castro      antitask         marina      1
4      community         castro      antitask         marina      2
11       diverse         castro      antitask         marina      2
32          nice         castro      antitask         marina      2
15           fun         castro      antitask         marina      9
1            bad         castro           bad         marina      1
5      community         castro           bad         marina      1
16           fun         castro           bad         marina      1
33          nice         castro           bad         marina      1
0       antitask         castro        boring         marina      1
2         boring         castro        boring         marina      1
17           fun         castro        boring         marina      1
25           gay         castro        boring         marina      1
34          nice         castro        boring         marina      1
40     normative         castro        boring         marina      1
42         other         castro        boring         marina      2
6      community         castro       chaotic         marina      1
35          nice         castro           fun         marina      1
36          nice         castro    gentrified         marina      1
43         other         castro    gentrified         marina      1
46       special         castro    gentrified         marina      2
12       diverse         castro    gentrified         marina      3
26           gay         castro    gentrified         marina      4
18           fun         castro    gentrified         marina      6
7      community         castro     geography         marina      2
27           gay         castro        gritty         marina      1
19           fun         castro  institutions         marina      1
20           fun         castro          nice         marina      1
37          nice         castro          nice         marina      1
41          open         castro          nice         marina      1
47       special         castro          nice         marina      1
8      community         castro     normative         marina      1
38          nice         castro     normative         marina      1
44         other         castro     normative         marina      1
13       diverse         castro     normative         marina      2
21           fun         castro     normative         marina      2
28           gay         castro     normative         marina      4
3         change         castro         other         marina      1
9      community         castro         other         marina      1
14       diverse         castro         other         marina      1
29           gay         castro         other         marina      1
39          nice         castro         other         marina      1
22           fun         castro         other         marina      2
23           fun         castro        sexual         marina      1
24           fun         castro       special         marina      1
10     community         castro         young         marina      2
30           gay         castro         young         marina      2

    probability
31     0.058824
45     0.058824
4      0.117647
11     0.117647
32     0.117647
15     0.529412
1      0.250000
5      0.250000
16     0.250000
33     0.250000
0      0.125000
2      0.125000
17     0.125000
25     0.125000
34     0.125000
40     0.125000
42     0.250000
6      1.000000
35     1.000000
36     0.058824
43     0.058824
46     0.117647
12     0.176471
26     0.235294
18     0.352941
7      1.000000
27     1.000000
19     1.000000
20     0.250000
37     0.250000
41     0.250000
47     0.250000
8      0.090909
38     0.090909
44     0.090909
13     0.181818
21     0.181818
28     0.363636
3      0.142857
9      0.142857
14     0.142857
29     0.142857
39     0.142857
22     0.285714
23     1.000000
24     1.000000
10     0.500000
30     0.500000
Forward probability of response2 given response1 for castro_res participants with response_site1=castro and response_site2=mission:
    category1 response_site1   category2 response_site2  count  probability
0    antitask         castro     special        mission      1     0.500000
1    antitask         castro     weather        mission      1     0.500000
2      boring         castro         fun        mission      1     1.000000
3     chaotic         castro     chaotic        mission      1     0.500000
4     chaotic         castro  gentrified        mission      1     0.500000
5   community         castro   community        mission      1     0.200000
7   community         castro  gentrified        mission      1     0.200000
8   community         castro     special        mission      1     0.200000
6   community         castro         fun        mission      2     0.400000
9     diverse         castro     chaotic        mission      1     0.142857
10    diverse         castro         fun        mission      1     0.142857
12    diverse         castro      gritty        mission      1     0.142857
13    diverse         castro        nice        mission      1     0.142857
14    diverse         castro     special        mission      1     0.142857
11    diverse         castro   geography        mission      2     0.285714
18        fun         castro  gentrified        mission      1     0.055556
19        fun         castro        nice        mission      1     0.055556
20        fun         castro     special        mission      1     0.055556
21        fun         castro     weather        mission      1     0.055556
15        fun         castro    antitask        mission      2     0.111111
16        fun         castro        food        mission      3     0.166667
17        fun         castro         fun        mission      9     0.500000
28        gay         castro   normative        mission      1     0.038462
31        gay         castro     weather        mission      1     0.038462
23        gay         castro     diverse        mission      2     0.076923
24        gay         castro        food        mission      2     0.076923
25        gay         castro         fun        mission      2     0.076923
29        gay         castro       other        mission      2     0.076923
30        gay         castro     special        mission      2     0.076923
22        gay         castro    antitask        mission      4     0.153846
26        gay         castro  gentrified        mission      4     0.153846
27        gay         castro      latino        mission      6     0.230769
32  geography         castro    antitask        mission      1     0.500000
33  geography         castro     special        mission      1     0.500000
34       nice         castro     chaotic        mission      1     0.166667
35       nice         castro     diverse        mission      1     0.166667
37       nice         castro  gentrified        mission      1     0.166667
38       nice         castro      gritty        mission      1     0.166667
36       nice         castro         fun        mission      2     0.333333
39       open         castro     chaotic        mission      1     1.000000
40      other         castro        food        mission      1     0.500000
41      other         castro      gritty        mission      1     0.500000
42     sexual         castro     diverse        mission      1     1.000000
43    special         castro    antitask        mission      1     0.200000
44    special         castro     diverse        mission      1     0.200000
45    special         castro        food        mission      1     0.200000
46    special         castro     special        mission      2     0.400000
Backward probability of response1 given response2 for castro_res participants with response_site1=castro and response_site2=mission:
    category1 response_site1   category2 response_site2  count  probability
32  geography         castro    antitask        mission      1     0.125000
43    special         castro    antitask        mission      1     0.125000
15        fun         castro    antitask        mission      2     0.250000
22        gay         castro    antitask        mission      4     0.500000
3     chaotic         castro     chaotic        mission      1     0.250000
9     diverse         castro     chaotic        mission      1     0.250000
34       nice         castro     chaotic        mission      1     0.250000
39       open         castro     chaotic        mission      1     0.250000
5   community         castro   community        mission      1     1.000000
35       nice         castro     diverse        mission      1     0.200000
42     sexual         castro     diverse        mission      1     0.200000
44    special         castro     diverse        mission      1     0.200000
23        gay         castro     diverse        mission      2     0.400000
40      other         castro        food        mission      1     0.142857
45    special         castro        food        mission      1     0.142857
24        gay         castro        food        mission      2     0.285714
16        fun         castro        food        mission      3     0.428571
2      boring         castro         fun        mission      1     0.058824
10    diverse         castro         fun        mission      1     0.058824
6   community         castro         fun        mission      2     0.117647
25        gay         castro         fun        mission      2     0.117647
36       nice         castro         fun        mission      2     0.117647
17        fun         castro         fun        mission      9     0.529412
4     chaotic         castro  gentrified        mission      1     0.125000
7   community         castro  gentrified        mission      1     0.125000
18        fun         castro  gentrified        mission      1     0.125000
37       nice         castro  gentrified        mission      1     0.125000
26        gay         castro  gentrified        mission      4     0.500000
11    diverse         castro   geography        mission      2     1.000000
12    diverse         castro      gritty        mission      1     0.333333
38       nice         castro      gritty        mission      1     0.333333
41      other         castro      gritty        mission      1     0.333333
27        gay         castro      latino        mission      6     1.000000
13    diverse         castro        nice        mission      1     0.500000
19        fun         castro        nice        mission      1     0.500000
28        gay         castro   normative        mission      1     1.000000
29        gay         castro       other        mission      2     1.000000
0    antitask         castro     special        mission      1     0.111111
8   community         castro     special        mission      1     0.111111
14    diverse         castro     special        mission      1     0.111111
20        fun         castro     special        mission      1     0.111111
33  geography         castro     special        mission      1     0.111111
30        gay         castro     special        mission      2     0.222222
46    special         castro     special        mission      2     0.222222
1    antitask         castro     weather        mission      1     0.333333
21        fun         castro     weather        mission      1     0.333333
31        gay         castro     weather        mission      1     0.333333

    category1 response_site1   category2 response_site2  count  probability
32  geography         castro    antitask        mission      1     0.125000
43    special         castro    antitask        mission      1     0.125000
15        fun         castro    antitask        mission      2     0.250000
22        gay         castro    antitask        mission      4     0.500000
3     chaotic         castro     chaotic        mission      1     0.250000
9     diverse         castro     chaotic        mission      1     0.250000
34       nice         castro     chaotic        mission      1     0.250000
39       open         castro     chaotic        mission      1     0.250000
5   community         castro   community        mission      1     1.000000
35       nice         castro     diverse        mission      1     0.200000
42     sexual         castro     diverse        mission      1     0.200000
44    special         castro     diverse        mission      1     0.200000
23        gay         castro     diverse        mission      2     0.400000
40      other         castro        food        mission      1     0.142857
45    special         castro        food        mission      1     0.142857
24        gay         castro        food        mission      2     0.285714
16        fun         castro        food        mission      3     0.428571
2      boring         castro         fun        mission      1     0.058824
10    diverse         castro         fun        mission      1     0.058824
6   community         castro         fun        mission      2     0.117647
25        gay         castro         fun        mission      2     0.117647
36       nice         castro         fun        mission      2     0.117647
17        fun         castro         fun        mission      9     0.529412
4     chaotic         castro  gentrified        mission      1     0.125000
7   community         castro  gentrified        mission      1     0.125000
18        fun         castro  gentrified        mission      1     0.125000
37       nice         castro  gentrified        mission      1     0.125000
26        gay         castro  gentrified        mission      4     0.500000
11    diverse         castro   geography        mission      2     1.000000
12    diverse         castro      gritty        mission      1     0.333333
38       nice         castro      gritty        mission      1     0.333333
41      other         castro      gritty        mission      1     0.333333
27        gay         castro      latino        mission      6     1.000000
13    diverse         castro        nice        mission      1     0.500000
19        fun         castro        nice        mission      1     0.500000
28        gay         castro   normative        mission      1     1.000000
29        gay         castro       other        mission      2     1.000000
0    antitask         castro     special        mission      1     0.111111
8   community         castro     special        mission      1     0.111111
14    diverse         castro     special        mission      1     0.111111
20        fun         castro     special        mission      1     0.111111
33  geography         castro     special        mission      1     0.111111
30        gay         castro     special        mission      2     0.222222
46    special         castro     special        mission      2     0.222222
1    antitask         castro     weather        mission      1     0.333333
21        fun         castro     weather        mission      1     0.333333
31        gay         castro     weather        mission      1     0.333333

## Castro Visitors

In [4]:
# Castro_vis participants with response_site1=castro and response_site2=marina
prob.forward_prob(df, target_fieldsite="castro_vis", target_r1_site="castro", target_r2_site="marina", count_filter=0)
prob.backward_prob(df, target_fieldsite="castro_vis", target_r1_site="castro", target_r2_site="marina", count_filter=0)

# Castro_vis participants with response_site1=castro and response_site2=mission
prob.forward_prob(df, target_fieldsite="castro_vis", target_r1_site="castro", target_r2_site="mission", count_filter=0)
prob.backward_prob(df, target_fieldsite="castro_vis", target_r1_site="castro", target_r2_site="mission", count_filter=0)

Forward probability of response2 given response1 for castro_vis participants with response_site1=castro and response_site2=marina:
    category1 response_site1   category2 response_site2  count  probability
1      boring         castro       other         marina      1     0.333333
0      boring         castro    antitask         marina      2     0.666667
2      change         castro       other         marina      1     1.000000
4     chaotic         castro      boring         marina      1     0.142857
5     chaotic         castro     chaotic         marina      1     0.142857
6     chaotic         castro  gentrified         marina      1     0.142857
3     chaotic         castro         bad         marina      2     0.285714
7     chaotic         castro   normative         marina      2     0.285714
8   community         castro  gentrified         marina      1     0.333333
9   community         castro      gritty         marina      1     0.333333
10  community         castro   normative         marina      1     0.333333
11        fun         castro    antitask         marina      1     0.045455
14        fun         castro   community         marina      1     0.045455
16        fun         castro      latino         marina      1     0.045455
17        fun         castro        nice         marina      1     0.045455
20        fun         castro       young         marina      1     0.045455
19        fun         castro       other         marina      2     0.090909
13        fun         castro      boring         marina      3     0.136364
15        fun         castro  gentrified         marina      3     0.136364
12        fun         castro         bad         marina      4     0.181818
18        fun         castro   normative         marina      5     0.227273
21        gay         castro    antitask         marina      1     0.032258
22        gay         castro         bad         marina      1     0.032258
23        gay         castro      boring         marina      1     0.032258
24        gay         castro         fun         marina      1     0.032258
25        gay         castro         gay         marina      1     0.032258
30        gay         castro     weather         marina      1     0.032258
27        gay         castro   geography         marina      2     0.064516
28        gay         castro        nice         marina      2     0.064516
26        gay         castro  gentrified         marina      7     0.225806
29        gay         castro   normative         marina     14     0.451613
31  geography         castro    antitask         marina      1     0.500000
32  geography         castro   geography         marina      1     0.500000
33       nice         castro      boring         marina      1     0.166667
34       nice         castro         fun         marina      1     0.166667
35       nice         castro  gentrified         marina      1     0.166667
36       nice         castro        nice         marina      1     0.166667
37       nice         castro   normative         marina      1     0.166667
38       nice         castro       other         marina      1     0.166667
39       open         castro         bad         marina      1     1.000000
40      other         castro        nice         marina      1     0.500000
41      other         castro       other         marina      1     0.500000
42    special         castro   normative         marina      1     0.500000
43    special         castro       other         marina      1     0.500000
Backward probability of response1 given response2 for castro_vis participants with response_site1=castro and response_site2=marina:
    category1 response_site1   category2 response_site2  count  probability
11        fun         castro    antitask         marina      1     0.200000
21        gay         castro    antitask         marina      1     0.200000
31  geography         castro    antitask         marina      1     0.200000
0      boring         castro    antitask         marina      2     0.400000
22        gay         castro         bad         marina      1     0.125000
39       open         castro         bad         marina      1     0.125000
3     chaotic         castro         bad         marina      2     0.250000
12        fun         castro         bad         marina      4     0.500000
4     chaotic         castro      boring         marina      1     0.166667
23        gay         castro      boring         marina      1     0.166667
33       nice         castro      boring         marina      1     0.166667
13        fun         castro      boring         marina      3     0.500000
5     chaotic         castro     chaotic         marina      1     1.000000
14        fun         castro   community         marina      1     1.000000
24        gay         castro         fun         marina      1     0.500000
34       nice         castro         fun         marina      1     0.500000
25        gay         castro         gay         marina      1     1.000000
6     chaotic         castro  gentrified         marina      1     0.076923
8   community         castro  gentrified         marina      1     0.076923
35       nice         castro  gentrified         marina      1     0.076923
15        fun         castro  gentrified         marina      3     0.230769
26        gay         castro  gentrified         marina      7     0.538462
32  geography         castro   geography         marina      1     0.333333
27        gay         castro   geography         marina      2     0.666667
9   community         castro      gritty         marina      1     1.000000
16        fun         castro      latino         marina      1     1.000000
17        fun         castro        nice         marina      1     0.200000
36       nice         castro        nice         marina      1     0.200000
40      other         castro        nice         marina      1     0.200000
28        gay         castro        nice         marina      2     0.400000
10  community         castro   normative         marina      1     0.041667
37       nice         castro   normative         marina      1     0.041667
42    special         castro   normative         marina      1     0.041667
7     chaotic         castro   normative         marina      2     0.083333
18        fun         castro   normative         marina      5     0.208333
29        gay         castro   normative         marina     14     0.583333
1      boring         castro       other         marina      1     0.142857
2      change         castro       other         marina      1     0.142857
38       nice         castro       other         marina      1     0.142857
41      other         castro       other         marina      1     0.142857
43    special         castro       other         marina      1     0.142857
19        fun         castro       other         marina      2     0.285714
30        gay         castro     weather         marina      1     1.000000
20        fun         castro       young         marina      1     1.000000
Forward probability of response2 given response1 for castro_vis participants with response_site1=castro and response_site2=mission:
    category1 response_site1     category2 response_site2  count  probability
0      boring         castro      antitask        mission      1     1.000000
1      change         castro       diverse        mission      1     1.000000
2     chaotic         castro        gritty        mission      1     0.500000
3     chaotic         castro          nice        mission      1     0.500000
4   community         castro    gentrified        mission      1     1.000000
6     diverse         castro          food        mission      1     0.333333
5     diverse         castro       diverse        mission      2     0.666667
7         fun         castro      antitask        mission      1     0.045455
12        fun         castro        gritty        mission      1     0.045455
13        fun         castro  institutions        mission      1     0.045455
14        fun         castro        latino        mission      1     0.045455
15        fun         castro          nice        mission      1     0.045455
16        fun         castro       special        mission      1     0.045455
10        fun         castro          food        mission      2     0.090909
8         fun         castro       chaotic        mission      3     0.136364
9         fun         castro       diverse        mission      5     0.227273
11        fun         castro           fun        mission      6     0.272727
17        gay         castro       actions        mission      1     0.030303
18        gay         castro       chaotic        mission      1     0.030303
19        gay         castro     community        mission      1     0.030303
23        gay         castro           gay        mission      1     0.030303
24        gay         castro    gentrified        mission      1     0.030303
28        gay         castro         other        mission      1     0.030303
30        gay         castro         young        mission      1     0.030303
21        gay         castro          food        mission      2     0.060606
22        gay         castro           fun        mission      2     0.060606
25        gay         castro        gritty        mission      2     0.060606
27        gay         castro          nice        mission      3     0.090909
29        gay         castro       special        mission      3     0.090909
20        gay         castro       diverse        mission      5     0.151515
26        gay         castro        latino        mission      9     0.272727
31       nice         castro      antitask        mission      1     0.200000
32       nice         castro          food        mission      1     0.200000
33       nice         castro           fun        mission      1     0.200000
34       nice         castro           gay        mission      2     0.400000
35  normative         castro          food        mission      1     1.000000
36       open         castro       diverse        mission      1     0.500000
37       open         castro           gay        mission      1     0.500000
38      other         castro       diverse        mission      1     0.333333
39      other         castro    gentrified        mission      2     0.666667
40     sexual         castro           bad        mission      1     0.333333
41     sexual         castro         other        mission      1     0.333333
42     sexual         castro        sexual        mission      1     0.333333
43    special         castro     community        mission      1     0.333333
44    special         castro        gritty        mission      1     0.333333
45    special         castro         other        mission      1     0.333333
Backward probability of response1 given response2 for castro_vis participants with response_site1=castro and response_site2=mission:
    category1 response_site1     category2 response_site2  count  probability
17        gay         castro       actions        mission      1     1.000000
0      boring         castro      antitask        mission      1     0.333333
7         fun         castro      antitask        mission      1     0.333333
31       nice         castro      antitask        mission      1     0.333333
40     sexual         castro           bad        mission      1     1.000000
18        gay         castro       chaotic        mission      1     0.250000
8         fun         castro       chaotic        mission      3     0.750000
19        gay         castro     community        mission      1     0.500000
43    special         castro     community        mission      1     0.500000
1      change         castro       diverse        mission      1     0.066667
36       open         castro       diverse        mission      1     0.066667
38      other         castro       diverse        mission      1     0.066667
5     diverse         castro       diverse        mission      2     0.133333
9         fun         castro       diverse        mission      5     0.333333
20        gay         castro       diverse        mission      5     0.333333
6     diverse         castro          food        mission      1     0.142857
32       nice         castro          food        mission      1     0.142857
35  normative         castro          food        mission      1     0.142857
10        fun         castro          food        mission      2     0.285714
21        gay         castro          food        mission      2     0.285714
33       nice         castro           fun        mission      1     0.111111
22        gay         castro           fun        mission      2     0.222222
11        fun         castro           fun        mission      6     0.666667
23        gay         castro           gay        mission      1     0.250000
37       open         castro           gay        mission      1     0.250000
34       nice         castro           gay        mission      2     0.500000
4   community         castro    gentrified        mission      1     0.250000
24        gay         castro    gentrified        mission      1     0.250000
39      other         castro    gentrified        mission      2     0.500000
2     chaotic         castro        gritty        mission      1     0.200000
12        fun         castro        gritty        mission      1     0.200000
44    special         castro        gritty        mission      1     0.200000
25        gay         castro        gritty        mission      2     0.400000
13        fun         castro  institutions        mission      1     1.000000
14        fun         castro        latino        mission      1     0.100000
26        gay         castro        latino        mission      9     0.900000
3     chaotic         castro          nice        mission      1     0.200000
15        fun         castro          nice        mission      1     0.200000
27        gay         castro          nice        mission      3     0.600000
28        gay         castro         other        mission      1     0.333333
41     sexual         castro         other        mission      1     0.333333
45    special         castro         other        mission      1     0.333333
42     sexual         castro        sexual        mission      1     1.000000
16        fun         castro       special        mission      1     0.250000
29        gay         castro       special        mission      3     0.750000
30        gay         castro         young        mission      1     1.000000

    category1 response_site1     category2 response_site2  count  probability
17        gay         castro       actions        mission      1     1.000000
0      boring         castro      antitask        mission      1     0.333333
7         fun         castro      antitask        mission      1     0.333333
31       nice         castro      antitask        mission      1     0.333333
40     sexual         castro           bad        mission      1     1.000000
18        gay         castro       chaotic        mission      1     0.250000
8         fun         castro       chaotic        mission      3     0.750000
19        gay         castro     community        mission      1     0.500000
43    special         castro     community        mission      1     0.500000
1      change         castro       diverse        mission      1     0.066667
36       open         castro       diverse        mission      1     0.066667
38      other         castro       diverse        mission      1     0.066667
5     diverse         castro       diverse        mission      2     0.133333
9         fun         castro       diverse        mission      5     0.333333
20        gay         castro       diverse        mission      5     0.333333
6     diverse         castro          food        mission      1     0.142857
32       nice         castro          food        mission      1     0.142857
35  normative         castro          food        mission      1     0.142857
10        fun         castro          food        mission      2     0.285714
21        gay         castro          food        mission      2     0.285714
33       nice         castro           fun        mission      1     0.111111
22        gay         castro           fun        mission      2     0.222222
11        fun         castro           fun        mission      6     0.666667
23        gay         castro           gay        mission      1     0.250000
37       open         castro           gay        mission      1     0.250000
34       nice         castro           gay        mission      2     0.500000
4   community         castro    gentrified        mission      1     0.250000
24        gay         castro    gentrified        mission      1     0.250000
39      other         castro    gentrified        mission      2     0.500000
2     chaotic         castro        gritty        mission      1     0.200000
12        fun         castro        gritty        mission      1     0.200000
44    special         castro        gritty        mission      1     0.200000
25        gay         castro        gritty        mission      2     0.400000
13        fun         castro  institutions        mission      1     1.000000
14        fun         castro        latino        mission      1     0.100000
26        gay         castro        latino        mission      9     0.900000
3     chaotic         castro          nice        mission      1     0.200000
15        fun         castro          nice        mission      1     0.200000
27        gay         castro          nice        mission      3     0.600000
28        gay         castro         other        mission      1     0.333333
41     sexual         castro         other        mission      1     0.333333
45    special         castro         other        mission      1     0.333333
42     sexual         castro        sexual        mission      1     1.000000
16        fun         castro       special        mission      1     0.250000
29        gay         castro       special        mission      3     0.750000
30        gay         castro         young        mission      1     1.000000

## Marina Residents

In [5]:
# Marina participants with response_site1=marina and response_site2=castro
prob.forward_prob(df, target_fieldsite="marina_res", target_r1_site="marina", target_r2_site="castro", count_filter=0)
prob.backward_prob(df, target_fieldsite="marina_res", target_r1_site="marina", target_r2_site="castro", count_filter=0)

# Marina participants with response_site1=marina and response_site2=mission
prob.forward_prob(df, target_fieldsite="marina_res", target_r1_site="castro", target_r2_site="marina", count_filter=0)
prob.backward_prob(df, target_fieldsite="marina_res", target_r1_site="castro", target_r2_site="marina", count_filter=0)

Forward probability of response2 given response1 for marina_res participants with response_site1=marina and response_site2=castro:
       category1 response_site1  category2 response_site2  count  probability
0        actions         marina   antitask         castro      1     1.000000
1            bad         marina     boring         castro      1     0.500000
2            bad         marina        gay         castro      1     0.500000
3         boring         marina        fun         castro      1     0.500000
4         boring         marina      other         castro      1     0.500000
5        chaotic         marina    diverse         castro      1     0.500000
6        chaotic         marina        fun         castro      1     0.500000
7      community         marina   antitask         castro      4     1.000000
8        diverse         marina       nice         castro      1     1.000000
12           fun         marina      other         castro      1     0.083333
10           fun         marina    diverse         castro      2     0.166667
9            fun         marina   antitask         castro      3     0.250000
11           fun         marina        fun         castro      6     0.500000
14    gentrified         marina    diverse         castro      1     0.066667
13    gentrified         marina   antitask         castro      2     0.133333
15    gentrified         marina        fun         castro      4     0.266667
16    gentrified         marina        gay         castro      8     0.533333
18     geography         marina  community         castro      1     0.142857
19     geography         marina        gay         castro      1     0.142857
17     geography         marina   antitask         castro      2     0.285714
20     geography         marina  geography         castro      3     0.428571
21  institutions         marina   antitask         castro      1     1.000000
23          nice         marina    chaotic         castro      1     0.071429
26          nice         marina       nice         castro      1     0.071429
27          nice         marina      other         castro      1     0.071429
24          nice         marina        fun         castro      3     0.214286
25          nice         marina        gay         castro      3     0.214286
22          nice         marina   antitask         castro      5     0.357143
28     normative         marina   antitask         castro      1     0.166667
29     normative         marina     boring         castro      1     0.166667
31     normative         marina       nice         castro      1     0.166667
32     normative         marina       open         castro      1     0.166667
30     normative         marina        fun         castro      2     0.333333
34         other         marina        fun         castro      1     0.166667
35         other         marina        gay         castro      2     0.333333
33         other         marina   antitask         castro      3     0.500000
36       special         marina        fun         castro      1     0.500000
37       special         marina      other         castro      1     0.500000
38       weather         marina   antitask         castro      1     1.000000
39         young         marina     change         castro      1     0.333333
40         young         marina        gay         castro      2     0.666667
Backward probability of response1 given response2 for marina_res participants with response_site1=marina and response_site2=castro:
       category1 response_site1  category2 response_site2  count  probability
0        actions         marina   antitask         castro      1     0.043478
21  institutions         marina   antitask         castro      1     0.043478
28     normative         marina   antitask         castro      1     0.043478
38       weather         marina   antitask         castro      1     0.043478
13    gentrified         marina   antitask         castro      2     0.086957
17     geography         marina   antitask         castro      2     0.086957
9            fun         marina   antitask         castro      3     0.130435
33         other         marina   antitask         castro      3     0.130435
7      community         marina   antitask         castro      4     0.173913
22          nice         marina   antitask         castro      5     0.217391
1            bad         marina     boring         castro      1     0.500000
29     normative         marina     boring         castro      1     0.500000
39         young         marina     change         castro      1     1.000000
23          nice         marina    chaotic         castro      1     1.000000
18     geography         marina  community         castro      1     1.000000
5        chaotic         marina    diverse         castro      1     0.250000
14    gentrified         marina    diverse         castro      1     0.250000
10           fun         marina    diverse         castro      2     0.500000
3         boring         marina        fun         castro      1     0.052632
6        chaotic         marina        fun         castro      1     0.052632
34         other         marina        fun         castro      1     0.052632
36       special         marina        fun         castro      1     0.052632
30     normative         marina        fun         castro      2     0.105263
24          nice         marina        fun         castro      3     0.157895
15    gentrified         marina        fun         castro      4     0.210526
11           fun         marina        fun         castro      6     0.315789
2            bad         marina        gay         castro      1     0.058824
19     geography         marina        gay         castro      1     0.058824
35         other         marina        gay         castro      2     0.117647
40         young         marina        gay         castro      2     0.117647
25          nice         marina        gay         castro      3     0.176471
16    gentrified         marina        gay         castro      8     0.470588
20     geography         marina  geography         castro      3     1.000000
8        diverse         marina       nice         castro      1     0.333333
26          nice         marina       nice         castro      1     0.333333
31     normative         marina       nice         castro      1     0.333333
32     normative         marina       open         castro      1     1.000000
4         boring         marina      other         castro      1     0.250000
12           fun         marina      other         castro      1     0.250000
27          nice         marina      other         castro      1     0.250000
37       special         marina      other         castro      1     0.250000
Forward probability of response2 given response1 for marina_res participants with response_site1=castro and response_site2=marina:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro       actions         marina      1
1       antitask         castro           fun         marina      1
3       antitask         castro     geography         marina      1
5       antitask         castro         other         marina      1
2       antitask         castro    gentrified         marina      2
4       antitask         castro          nice         marina      2
6         boring         castro           fun         marina      1
7        diverse         castro          nice         marina      1
8        diverse         castro         young         marina      1
9            fun         castro       actions         marina      1
10           fun         castro        boring         marina      1
12           fun         castro       diverse         marina      1
14           fun         castro    gentrified         marina      1
16           fun         castro  institutions         marina      1
19           fun         castro         other         marina      1
11           fun         castro       chaotic         marina      2
13           fun         castro           fun         marina      2
15           fun         castro     geography         marina      2
18           fun         castro     normative         marina      3
20           fun         castro         young         marina      3
17           fun         castro          nice         marina      4
21           gay         castro      antitask         marina      1
22           gay         castro        boring         marina      1
24           gay         castro     geography         marina      1
25           gay         castro          nice         marina      1
28           gay         castro         young         marina      1
27           gay         castro         other         marina      4
26           gay         castro     normative         marina      8
23           gay         castro    gentrified         marina     10
29     geography         castro    gentrified         marina      1
30     geography         castro     geography         marina      1
31  institutions         castro           fun         marina      1
32  institutions         castro     geography         marina      1
33  institutions         castro  institutions         marina      1
34  institutions         castro         other         marina      2
35          nice         castro        change         marina      1
36          nice         castro          nice         marina      1
37         other         castro       actions         marina      1
38         other         castro         other         marina      1
39         other         castro         young         marina      1
40       special         castro          nice         marina      1

    probability
0      0.125000
1      0.125000
3      0.125000
5      0.125000
2      0.250000
4      0.250000
6      1.000000
7      0.500000
8      0.500000
9      0.045455
10     0.045455
12     0.045455
14     0.045455
16     0.045455
19     0.045455
11     0.090909
13     0.090909
15     0.090909
18     0.136364
20     0.136364
17     0.181818
21     0.037037
22     0.037037
24     0.037037
25     0.037037
28     0.037037
27     0.148148
26     0.296296
23     0.370370
29     0.500000
30     0.500000
31     0.200000
32     0.200000
33     0.200000
34     0.400000
35     0.500000
36     0.500000
37     0.333333
38     0.333333
39     0.333333
40     1.000000
Backward probability of response1 given response2 for marina_res participants with response_site1=castro and response_site2=marina:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro       actions         marina      1
9            fun         castro       actions         marina      1
37         other         castro       actions         marina      1
21           gay         castro      antitask         marina      1
10           fun         castro        boring         marina      1
22           gay         castro        boring         marina      1
35          nice         castro        change         marina      1
11           fun         castro       chaotic         marina      2
12           fun         castro       diverse         marina      1
1       antitask         castro           fun         marina      1
6         boring         castro           fun         marina      1
31  institutions         castro           fun         marina      1
13           fun         castro           fun         marina      2
14           fun         castro    gentrified         marina      1
29     geography         castro    gentrified         marina      1
2       antitask         castro    gentrified         marina      2
23           gay         castro    gentrified         marina     10
3       antitask         castro     geography         marina      1
24           gay         castro     geography         marina      1
30     geography         castro     geography         marina      1
32  institutions         castro     geography         marina      1
15           fun         castro     geography         marina      2
16           fun         castro  institutions         marina      1
33  institutions         castro  institutions         marina      1
7        diverse         castro          nice         marina      1
25           gay         castro          nice         marina      1
36          nice         castro          nice         marina      1
40       special         castro          nice         marina      1
4       antitask         castro          nice         marina      2
17           fun         castro          nice         marina      4
18           fun         castro     normative         marina      3
26           gay         castro     normative         marina      8
5       antitask         castro         other         marina      1
19           fun         castro         other         marina      1
38         other         castro         other         marina      1
34  institutions         castro         other         marina      2
27           gay         castro         other         marina      4
8        diverse         castro         young         marina      1
28           gay         castro         young         marina      1
39         other         castro         young         marina      1
20           fun         castro         young         marina      3

    probability
0      0.333333
9      0.333333
37     0.333333
21     1.000000
10     0.500000
22     0.500000
35     1.000000
11     1.000000
12     1.000000
1      0.200000
6      0.200000
31     0.200000
13     0.400000
14     0.071429
29     0.071429
2      0.142857
23     0.714286
3      0.166667
24     0.166667
30     0.166667
32     0.166667
15     0.333333
16     0.500000
33     0.500000
7      0.100000
25     0.100000
36     0.100000
40     0.100000
4      0.200000
17     0.400000
18     0.272727
26     0.727273
5      0.111111
19     0.111111
38     0.111111
34     0.222222
27     0.444444
8      0.166667
28     0.166667
39     0.166667
20     0.500000

,category1,response_site1,category2,response_site2,count,probability
0,antitask,castro,actions,marina,1,0.333333
9,fun,castro,actions,marina,1,0.333333
37,other,castro,actions,marina,1,0.333333
21,gay,castro,antitask,marina,1,1.000000
10,fun,castro,boring,marina,1,0.500000
22,gay,castro,boring,marina,1,0.500000
35,nice,castro,change,marina,1,1.000000
11,fun,castro,chaotic,marina,2,1.000000
12,fun,castro,diverse,marina,1,1.000000
1,antitask,castro,fun,marina,1,0.200000
6,boring,castro,fun,marina,1,0.200000
31,institutions,castro,fun,marina,1,0.200000
13,fun,castro,fun,marina,2,0.400000
14,fun,castro,gentrified,marina,1,0.071429
29,geography,castro,gentrified,marina,1,0.071429
2,antitask,castro,gentrified,marina,2,0.142857
23,gay,castro,gentrified,marina,10,0.714286
3,antitask,castro,geography,marina,1,0.166667
24,gay,castro,geography,marina,1,0.166667
30,geography,castro,geography,marina,1,0.166667
32,institutions,castro,geography,marina,1,0.166667
15,fun,castro,geography,marina,2,0.333333
16,fun,castro,institutions,marina,1,0.500000
33,institutions,castro,institutions,marina,1,0.500000
7,diverse,castro,nice,marina,1,0.100000
25,gay,castro,nice,marina,1,0.100000
36,nice,castro,nice,marina,1,0.100000
40,special,castro,nice,marina,1,0.100000
4,antitask,castro,nice,marina,2,0.200000
17,fun,castro,nice,marina,4,0.400000
18,fun,castro,normative,marina,3,0.272727
26,gay,castro,normative,marina,8,0.727273
5,antitask,castro,other,marina,1,0.111111
19,fun,castro,other,marina,1,0.111111
38,other,castro,other,marina,1,0.111111
34,institutions,castro,other,marina,2,0.222222
27,gay,castro,other,marina,4,0.444444
8,diverse,castro,young,marina,1,0.166667
28,gay,castro,young,marina,1,0.166667
39,other,castro,young,marina,1,0.166667
20,fun,castro,young,marina,3,0.500000

## Mission Residents

In [6]:
# Mission participants with response_site1=mission and response_site2=castro
prob.forward_prob(df, target_fieldsite="mission_res", target_r1_site="mission", target_r2_site="castro", count_filter=0)
prob.backward_prob(df, target_fieldsite="mission_res", target_r1_site="mission", target_r2_site="castro", count_filter=0)

# Mission participants with response_site1=castro and response_site2=mission
prob.forward_prob(df, target_fieldsite="mission_res", target_r1_site="castro", target_r2_site="mission", count_filter=0)
prob.backward_prob(df, target_fieldsite="mission_res", target_r1_site="castro", target_r2_site="mission", count_filter=0)

Forward probability of response2 given response1 for mission_res participants with response_site1=mission and response_site2=castro:
     category1 response_site1   category2 response_site2  count  probability
0          bad        mission         gay         castro      1     1.000000
1      chaotic        mission         fun         castro      1     1.000000
3    community        mission         fun         castro      1     0.166667
4    community        mission   geography         castro      1     0.166667
5    community        mission        nice         castro      1     0.166667
6    community        mission     special         castro      1     0.166667
2    community        mission   community         castro      2     0.333333
10     diverse        mission  gentrified         castro      1     0.083333
7      diverse        mission     diverse         castro      2     0.166667
9      diverse        mission         gay         castro      3     0.250000
8      diverse        mission         fun         castro      6     0.500000
11         fun        mission      boring         castro      1     0.055556
12         fun        mission   community         castro      1     0.055556
17         fun        mission     special         castro      1     0.055556
13         fun        mission     diverse         castro      2     0.111111
15         fun        mission         gay         castro      2     0.111111
16         fun        mission        nice         castro      2     0.111111
14         fun        mission         fun         castro      9     0.500000
19  gentrified        mission  gentrified         castro      1     0.333333
18  gentrified        mission         gay         castro      2     0.666667
20   geography        mission         gay         castro      1     1.000000
21      gritty        mission         gay         castro      2     0.500000
22      gritty        mission        nice         castro      2     0.500000
26      latino        mission      sexual         castro      1     0.125000
23      latino        mission   community         castro      2     0.250000
24      latino        mission         gay         castro      2     0.250000
25      latino        mission       other         castro      3     0.375000
27        nice        mission     chaotic         castro      1     0.083333
28        nice        mission         fun         castro      1     0.083333
30        nice        mission   geography         castro      1     0.083333
29        nice        mission         gay         castro      2     0.166667
31        nice        mission        nice         castro      7     0.583333
33       other        mission         fun         castro      1     0.250000
34       other        mission         gay         castro      1     0.250000
32       other        mission     diverse         castro      2     0.500000
37     special        mission         fun         castro      1     0.076923
39     special        mission        nice         castro      1     0.076923
42     special        mission     special         castro      1     0.076923
35     special        mission    antitask         castro      2     0.153846
36     special        mission     diverse         castro      2     0.153846
38     special        mission         gay         castro      2     0.153846
40     special        mission        open         castro      2     0.153846
41     special        mission       other         castro      2     0.153846
43     weather        mission     diverse         castro      1     1.000000
Backward probability of response1 given response2 for mission_res participants with response_site1=mission and response_site2=castro:
     category1 response_site1   category2 response_site2  count  probability
35     special        mission    antitask         castro      2     1.000000
11         fun        mission      boring         castro      1     1.000000
27        nice        mission     chaotic         castro      1     1.000000
12         fun        mission   community         castro      1     0.200000
2    community        mission   community         castro      2     0.400000
23      latino        mission   community         castro      2     0.400000
43     weather        mission     diverse         castro      1     0.111111
7      diverse        mission     diverse         castro      2     0.222222
13         fun        mission     diverse         castro      2     0.222222
32       other        mission     diverse         castro      2     0.222222
36     special        mission     diverse         castro      2     0.222222
1      chaotic        mission         fun         castro      1     0.050000
3    community        mission         fun         castro      1     0.050000
28        nice        mission         fun         castro      1     0.050000
33       other        mission         fun         castro      1     0.050000
37     special        mission         fun         castro      1     0.050000
8      diverse        mission         fun         castro      6     0.300000
14         fun        mission         fun         castro      9     0.450000
0          bad        mission         gay         castro      1     0.055556
20   geography        mission         gay         castro      1     0.055556
34       other        mission         gay         castro      1     0.055556
15         fun        mission         gay         castro      2     0.111111
18  gentrified        mission         gay         castro      2     0.111111
21      gritty        mission         gay         castro      2     0.111111
24      latino        mission         gay         castro      2     0.111111
29        nice        mission         gay         castro      2     0.111111
38     special        mission         gay         castro      2     0.111111
9      diverse        mission         gay         castro      3     0.166667
10     diverse        mission  gentrified         castro      1     0.500000
19  gentrified        mission  gentrified         castro      1     0.500000
4    community        mission   geography         castro      1     0.500000
30        nice        mission   geography         castro      1     0.500000
5    community        mission        nice         castro      1     0.076923
39     special        mission        nice         castro      1     0.076923
16         fun        mission        nice         castro      2     0.153846
22      gritty        mission        nice         castro      2     0.153846
31        nice        mission        nice         castro      7     0.538462
40     special        mission        open         castro      2     1.000000
41     special        mission       other         castro      2     0.400000
25      latino        mission       other         castro      3     0.600000
26      latino        mission      sexual         castro      1     1.000000
6    community        mission     special         castro      1     0.333333
17         fun        mission     special         castro      1     0.333333
42     special        mission     special         castro      1     0.333333
Forward probability of response2 given response1 for mission_res participants with response_site1=castro and response_site2=mission:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro       diverse        mission      1
1       antitask         castro    gentrified        mission      1
2       antitask         castro        latino        mission      1
3       antitask         castro          nice        mission      1
4            bad         castro         other        mission      1
5        chaotic         castro          food        mission      2
6        diverse         castro      antitask        mission      1
8        diverse         castro          food        mission      1
9        diverse         castro           fun        mission      1
7        diverse         castro       diverse        mission      2
10       diverse         castro        latino        mission      2
11           fun         castro      antitask        mission      1
12           fun         castro     community        mission      1
16           fun         castro        gritty        mission      1
17           fun         castro  institutions        mission      1
13           fun         castro       diverse        mission      2
14           fun         castro          food        mission      2
15           fun         castro           fun        mission     11
19           gay         castro     community        mission      1
21           gay         castro          food        mission      1
23           gay         castro        gritty        mission      1
25           gay         castro         other        mission      1
26           gay         castro       weather        mission      1
18           gay         castro      antitask        mission      5
24           gay         castro        latino        mission      5
22           gay         castro           fun        mission      7
20           gay         castro       diverse        mission      8
27    gentrified         castro    gentrified        mission      1
28     geography         castro     geography        mission      1
29     geography         castro        latino        mission      1
30        gritty         castro        gritty        mission      1
31  institutions         castro        latino        mission      1
32          nice         castro       diverse        mission      1
33          nice         castro    gentrified        mission      1
34          nice         castro        gritty        mission      1
35          nice         castro          nice        mission      1
36     normative         castro        gritty        mission      1
37     normative         castro     normative        mission      1
38         other         castro           bad        mission      1
40         other         castro        latino        mission      1
39         other         castro       diverse        mission      2
41       special         castro        latino        mission      1
42       special         castro          nice        mission      1
43       special         castro       special        mission      2

    probability
0      0.250000
1      0.250000
2      0.250000
3      0.250000
4      1.000000
5      1.000000
6      0.142857
8      0.142857
9      0.142857
7      0.285714
10     0.285714
11     0.052632
12     0.052632
16     0.052632
17     0.052632
13     0.105263
14     0.105263
15     0.578947
19     0.033333
21     0.033333
23     0.033333
25     0.033333
26     0.033333
18     0.166667
24     0.166667
22     0.233333
20     0.266667
27     1.000000
28     0.500000
29     0.500000
30     1.000000
31     1.000000
32     0.250000
33     0.250000
34     0.250000
35     0.250000
36     0.500000
37     0.500000
38     0.250000
40     0.250000
39     0.500000
41     0.250000
42     0.250000
43     0.500000
Backward probability of response1 given response2 for mission_res participants with response_site1=castro and response_site2=mission:
       category1 response_site1     category2 response_site2  count  \
6        diverse         castro      antitask        mission      1
11           fun         castro      antitask        mission      1
18           gay         castro      antitask        mission      5
38         other         castro           bad        mission      1
12           fun         castro     community        mission      1
19           gay         castro     community        mission      1
0       antitask         castro       diverse        mission      1
32          nice         castro       diverse        mission      1
7        diverse         castro       diverse        mission      2
13           fun         castro       diverse        mission      2
39         other         castro       diverse        mission      2
20           gay         castro       diverse        mission      8
8        diverse         castro          food        mission      1
21           gay         castro          food        mission      1
5        chaotic         castro          food        mission      2
14           fun         castro          food        mission      2
9        diverse         castro           fun        mission      1
22           gay         castro           fun        mission      7
15           fun         castro           fun        mission     11
1       antitask         castro    gentrified        mission      1
27    gentrified         castro    gentrified        mission      1
33          nice         castro    gentrified        mission      1
28     geography         castro     geography        mission      1
16           fun         castro        gritty        mission      1
23           gay         castro        gritty        mission      1
30        gritty         castro        gritty        mission      1
34          nice         castro        gritty        mission      1
36     normative         castro        gritty        mission      1
17           fun         castro  institutions        mission      1
2       antitask         castro        latino        mission      1
29     geography         castro        latino        mission      1
31  institutions         castro        latino        mission      1
40         other         castro        latino        mission      1
41       special         castro        latino        mission      1
10       diverse         castro        latino        mission      2
24           gay         castro        latino        mission      5
3       antitask         castro          nice        mission      1
35          nice         castro          nice        mission      1
42       special         castro          nice        mission      1
37     normative         castro     normative        mission      1
4            bad         castro         other        mission      1
25           gay         castro         other        mission      1
43       special         castro       special        mission      2
26           gay         castro       weather        mission      1

    probability
6      0.142857
11     0.142857
18     0.714286
38     1.000000
12     0.500000
19     0.500000
0      0.062500
32     0.062500
7      0.125000
13     0.125000
39     0.125000
20     0.500000
8      0.166667
21     0.166667
5      0.333333
14     0.333333
9      0.052632
22     0.368421
15     0.578947
1      0.333333
27     0.333333
33     0.333333
28     1.000000
16     0.200000
23     0.200000
30     0.200000
34     0.200000
36     0.200000
17     1.000000
2      0.083333
29     0.083333
31     0.083333
40     0.083333
41     0.083333
10     0.166667
24     0.416667
3      0.333333
35     0.333333
42     0.333333
37     1.000000
4      0.500000
25     0.500000
43     1.000000
26     1.000000

,category1,response_site1,category2,response_site2,count,probability
6,diverse,castro,antitask,mission,1,0.142857
11,fun,castro,antitask,mission,1,0.142857
18,gay,castro,antitask,mission,5,0.714286
38,other,castro,bad,mission,1,1.000000
12,fun,castro,community,mission,1,0.500000
19,gay,castro,community,mission,1,0.500000
0,antitask,castro,diverse,mission,1,0.062500
32,nice,castro,diverse,mission,1,0.062500
7,diverse,castro,diverse,mission,2,0.125000
13,fun,castro,diverse,mission,2,0.125000
39,other,castro,diverse,mission,2,0.125000
20,gay,castro,diverse,mission,8,0.500000
8,diverse,castro,food,mission,1,0.166667
21,gay,castro,food,mission,1,0.166667
5,chaotic,castro,food,mission,2,0.333333
14,fun,castro,food,mission,2,0.333333
9,diverse,castro,fun,mission,1,0.052632
22,gay,castro,fun,mission,7,0.368421
15,fun,castro,fun,mission,11,0.578947
1,antitask,castro,gentrified,mission,1,0.333333
27,gentrified,castro,gentrified,mission,1,0.333333
33,nice,castro,gentrified,mission,1,0.333333
28,geography,castro,geography,mission,1,1.000000
16,fun,castro,gritty,mission,1,0.200000
23,gay,castro,gritty,mission,1,0.200000
30,gritty,castro,gritty,mission,1,0.200000
34,nice,castro,gritty,mission,1,0.200000
36,normative,castro,gritty,mission,1,0.200000
17,fun,castro,institutions,mission,1,1.000000
2,antitask,castro,latino,mission,1,0.083333
29,geography,castro,latino,mission,1,0.083333
31,institutions,castro,latino,mission,1,0.083333
40,other,castro,latino,mission,1,0.083333
41,special,castro,latino,mission,1,0.083333
10,diverse,castro,latino,mission,2,0.166667
24,gay,castro,latino,mission,5,0.416667
3,antitask,castro,nice,mission,1,0.333333
35,nice,castro,nice,mission,1,0.333333
42,special,castro,nice,mission,1,0.333333
37,normative,castro,normative,mission,1,1.000000
4,bad,castro,other,mission,1,0.500000
25,gay,castro,other,mission,1,0.500000
43,special,castro,special,mission,2,1.000000
26,gay,castro,weather,mission,1,1.000000

## Collapsed across fieldsite

In [7]:
df_fwd_castro_marina = prob.forward_prob(df, target_r1_site="castro", target_r2_site="marina", count_filter=0,filter_fieldsite=False)
df_bwd_castro_marina = prob.backward_prob(df, target_r1_site="castro", target_r2_site="marina", count_filter=0,filter_fieldsite=False)

df_fwd_castro_mission = prob.forward_prob(df, target_r1_site="castro", target_r2_site="mission", count_filter=0,filter_fieldsite=False)
df_bwd_castro_mission = prob.backward_prob(df, target_r1_site="castro", target_r2_site="mission", count_filter=0,filter_fieldsite=False)

Forward probability of response2 given response1 for None participants with response_site1=castro and response_site2=marina:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro       actions         marina      1
1       antitask         castro        boring         marina      1
2       antitask         castro           fun         marina      1
4       antitask         castro     geography         marina      1
6       antitask         castro         other         marina      1
3       antitask         castro    gentrified         marina      2
5       antitask         castro          nice         marina      2
7            bad         castro           bad         marina      1
9         boring         castro        boring         marina      1
10        boring         castro           fun         marina      1
11        boring         castro         other         marina      1
8         boring         castro      antitask         marina      2
12        change         castro         other         marina      2
14       chaotic         castro        boring         marina      1
15       chaotic         castro       chaotic         marina      1
16       chaotic         castro    gentrified         marina      1
13       chaotic         castro           bad         marina      2
17       chaotic         castro     normative         marina      2
19     community         castro           bad         marina      1
20     community         castro       chaotic         marina      1
21     community         castro    gentrified         marina      1
23     community         castro        gritty         marina      1
25     community         castro         other         marina      1
18     community         castro      antitask         marina      2
22     community         castro     geography         marina      2
24     community         castro     normative         marina      2
26     community         castro         young         marina      2
29       diverse         castro          nice         marina      1
31       diverse         castro         other         marina      1
32       diverse         castro         young         marina      1
27       diverse         castro      antitask         marina      2
30       diverse         castro     normative         marina      2
28       diverse         castro    gentrified         marina      3
33           fun         castro       actions         marina      1
38           fun         castro     community         marina      1
39           fun         castro       diverse         marina      1
44           fun         castro        latino         marina      1
48           fun         castro        sexual         marina      1
49           fun         castro       special         marina      1
37           fun         castro       chaotic         marina      2
40           fun         castro           fun         marina      2
42           fun         castro     geography         marina      2
43           fun         castro  institutions         marina      2
50           fun         castro         young         marina      4
35           fun         castro           bad         marina      5
36           fun         castro        boring         marina      5
47           fun         castro         other         marina      5
45           fun         castro          nice         marina      6
34           fun         castro      antitask         marina     10
41           fun         castro    gentrified         marina     10
46           fun         castro     normative         marina     10
52           gay         castro           bad         marina      1
54           gay         castro           fun         marina      1
55           gay         castro           gay         marina      1
58           gay         castro        gritty         marina      1
62           gay         castro       weather         marina      1
51           gay         castro      antitask         marina      2
53           gay         castro        boring         marina      3
57           gay         castro     geography         marina      3
59           gay         castro          nice         marina      3
63           gay         castro         young         marina      3
61           gay         castro         other         marina      5
56           gay         castro    gentrified         marina     21
60           gay         castro     normative         marina     26
64     geography         castro      antitask         marina      1
65     geography         castro    gentrified         marina      1
66     geography         castro     geography         marina      2
67  institutions         castro      antitask         marina      1
68  institutions         castro           fun         marina      1
69  institutions         castro     geography         marina      1
70  institutions         castro  institutions         marina      1
71  institutions         castro         other         marina      2
73          nice         castro           bad         marina      1
75          nice         castro        change         marina      1
72          nice         castro      antitask         marina      2
74          nice         castro        boring         marina      2
76          nice         castro           fun         marina      2
77          nice         castro    gentrified         marina      2
79          nice         castro     normative         marina      2
80          nice         castro         other         marina      2
78          nice         castro          nice         marina      3
81     normative         castro        boring         marina      1
82          open         castro           bad         marina      1
83          open         castro          nice         marina      1
84         other         castro       actions         marina      1
86         other         castro    gentrified         marina      1
87         other         castro          nice         marina      1
88         other         castro     normative         marina      1
90         other         castro         young         marina      1
85         other         castro        boring         marina      2
89         other         castro         other         marina      2
91       special         castro      antitask         marina      1
94       special         castro     normative         marina      1
95       special         castro         other         marina      1
92       special         castro    gentrified         marina      2
93       special         castro          nice         marina      2

    probability
0      0.111111
1      0.111111
2      0.111111
4      0.111111
6      0.111111
3      0.222222
5      0.222222
7      1.000000
9      0.200000
10     0.200000
11     0.200000
8      0.400000
12     1.000000
14     0.142857
15     0.142857
16     0.142857
13     0.285714
17     0.285714
19     0.076923
20     0.076923
21     0.076923
23     0.076923
25     0.076923
18     0.153846
22     0.153846
24     0.153846
26     0.153846
29     0.100000
31     0.100000
32     0.100000
27     0.200000
30     0.200000
28     0.300000
33     0.014493
38     0.014493
39     0.014493
44     0.014493
48     0.014493
49     0.014493
37     0.028986
40     0.028986
42     0.028986
43     0.028986
50     0.057971
35     0.072464
36     0.072464
47     0.072464
45     0.086957
34     0.144928
41     0.144928
46     0.144928
52     0.014085
54     0.014085
55     0.014085
58     0.014085
62     0.014085
51     0.028169
53     0.042254
57     0.042254
59     0.042254
63     0.042254
61     0.070423
56     0.295775
60     0.366197
64     0.250000
65     0.250000
66     0.500000
67     0.166667
68     0.166667
69     0.166667
70     0.166667
71     0.333333
73     0.058824
75     0.058824
72     0.117647
74     0.117647
76     0.117647
77     0.117647
79     0.117647
80     0.117647
78     0.176471
81     1.000000
82     0.500000
83     0.500000
84     0.111111
86     0.111111
87     0.111111
88     0.111111
90     0.111111
85     0.222222
89     0.222222
91     0.142857
94     0.142857
95     0.142857
92     0.285714
93     0.285714
Backward probability of response1 given response2 for None participants with response_site1=castro and response_site2=marina:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro       actions         marina      1
33           fun         castro       actions         marina      1
84         other         castro       actions         marina      1
64     geography         castro      antitask         marina      1
67  institutions         castro      antitask         marina      1
91       special         castro      antitask         marina      1
8         boring         castro      antitask         marina      2
18     community         castro      antitask         marina      2
27       diverse         castro      antitask         marina      2
51           gay         castro      antitask         marina      2
72          nice         castro      antitask         marina      2
34           fun         castro      antitask         marina     10
7            bad         castro           bad         marina      1
19     community         castro           bad         marina      1
52           gay         castro           bad         marina      1
73          nice         castro           bad         marina      1
82          open         castro           bad         marina      1
13       chaotic         castro           bad         marina      2
35           fun         castro           bad         marina      5
1       antitask         castro        boring         marina      1
9         boring         castro        boring         marina      1
14       chaotic         castro        boring         marina      1
81     normative         castro        boring         marina      1
74          nice         castro        boring         marina      2
85         other         castro        boring         marina      2
53           gay         castro        boring         marina      3
36           fun         castro        boring         marina      5
75          nice         castro        change         marina      1
15       chaotic         castro       chaotic         marina      1
20     community         castro       chaotic         marina      1
37           fun         castro       chaotic         marina      2
38           fun         castro     community         marina      1
39           fun         castro       diverse         marina      1
2       antitask         castro           fun         marina      1
10        boring         castro           fun         marina      1
54           gay         castro           fun         marina      1
68  institutions         castro           fun         marina      1
40           fun         castro           fun         marina      2
76          nice         castro           fun         marina      2
55           gay         castro           gay         marina      1
16       chaotic         castro    gentrified         marina      1
21     community         castro    gentrified         marina      1
65     geography         castro    gentrified         marina      1
86         other         castro    gentrified         marina      1
3       antitask         castro    gentrified         marina      2
77          nice         castro    gentrified         marina      2
92       special         castro    gentrified         marina      2
28       diverse         castro    gentrified         marina      3
41           fun         castro    gentrified         marina     10
56           gay         castro    gentrified         marina     21
4       antitask         castro     geography         marina      1
69  institutions         castro     geography         marina      1
22     community         castro     geography         marina      2
42           fun         castro     geography         marina      2
66     geography         castro     geography         marina      2
57           gay         castro     geography         marina      3
23     community         castro        gritty         marina      1
58           gay         castro        gritty         marina      1
70  institutions         castro  institutions         marina      1
43           fun         castro  institutions         marina      2
44           fun         castro        latino         marina      1
29       diverse         castro          nice         marina      1
83          open         castro          nice         marina      1
87         other         castro          nice         marina      1
5       antitask         castro          nice         marina      2
93       special         castro          nice         marina      2
59           gay         castro          nice         marina      3
78          nice         castro          nice         marina      3
45           fun         castro          nice         marina      6
88         other         castro     normative         marina      1
94       special         castro     normative         marina      1
17       chaotic         castro     normative         marina      2
24     community         castro     normative         marina      2
30       diverse         castro     normative         marina      2
79          nice         castro     normative         marina      2
46           fun         castro     normative         marina     10
60           gay         castro     normative         marina     26
6       antitask         castro         other         marina      1
11        boring         castro         other         marina      1
25     community         castro         other         marina      1
31       diverse         castro         other         marina      1
95       special         castro         other         marina      1
12        change         castro         other         marina      2
71  institutions         castro         other         marina      2
80          nice         castro         other         marina      2
89         other         castro         other         marina      2
47           fun         castro         other         marina      5
61           gay         castro         other         marina      5
48           fun         castro        sexual         marina      1
49           fun         castro       special         marina      1
62           gay         castro       weather         marina      1
32       diverse         castro         young         marina      1
90         other         castro         young         marina      1
26     community         castro         young         marina      2
63           gay         castro         young         marina      3
50           fun         castro         young         marina      4

    probability
0      0.333333
33     0.333333
84     0.333333
64     0.043478
67     0.043478
91     0.043478
8      0.086957
18     0.086957
27     0.086957
51     0.086957
72     0.086957
34     0.434783
7      0.083333
19     0.083333
52     0.083333
73     0.083333
82     0.083333
13     0.166667
35     0.416667
1      0.062500
9      0.062500
14     0.062500
81     0.062500
74     0.125000
85     0.125000
53     0.187500
36     0.312500
75     1.000000
15     0.250000
20     0.250000
37     0.500000
38     1.000000
39     1.000000
2      0.125000
10     0.125000
54     0.125000
68     0.125000
40     0.250000
76     0.250000
55     1.000000
16     0.022727
21     0.022727
65     0.022727
86     0.022727
3      0.045455
77     0.045455
92     0.045455
28     0.068182
41     0.227273
56     0.477273
4      0.090909
69     0.090909
22     0.181818
42     0.181818
66     0.181818
57     0.272727
23     0.500000
58     0.500000
70     0.333333
43     0.666667
44     1.000000
29     0.052632
83     0.052632
87     0.052632
5      0.105263
93     0.105263
59     0.157895
78     0.157895
45     0.315789
88     0.021739
94     0.021739
17     0.043478
24     0.043478
30     0.043478
79     0.043478
46     0.217391
60     0.565217
6      0.043478
11     0.043478
25     0.043478
31     0.043478
95     0.043478
12     0.086957
71     0.086957
80     0.086957
89     0.086957
47     0.217391
61     0.217391
48     1.000000
49     1.000000
62     1.000000
32     0.090909
90     0.090909
26     0.181818
63     0.272727
50     0.363636
Forward probability of response2 given response1 for None participants with response_site1=castro and response_site2=mission:
       category1 response_site1     category2 response_site2  count  \
0       antitask         castro       diverse        mission      1
1       antitask         castro    gentrified        mission      1
2       antitask         castro        latino        mission      1
3       antitask         castro          nice        mission      1
4       antitask         castro       special        mission      1
5       antitask         castro       weather        mission      1
6            bad         castro         other        mission      1
7         boring         castro      antitask        mission      1
8         boring         castro           fun        mission      1
9         change         castro       diverse        mission      1
10       chaotic         castro       chaotic        mission      1
12       chaotic         castro    gentrified        mission      1
13       chaotic         castro        gritty        mission      1
14       chaotic         castro          nice        mission      1
11       chaotic         castro          food        mission      2
15     community         castro     community        mission      1
18     community         castro       special        mission      1
16     community         castro           fun        mission      2
17     community         castro    gentrified        mission      2
19       diverse         castro      antitask        mission      1
20       diverse         castro       chaotic        mission      1
25       diverse         castro        gritty        mission      1
27       diverse         castro          nice        mission      1
28       diverse         castro       special        mission      1
22       diverse         castro          food        mission      2
23       diverse         castro           fun        mission      2
24       diverse         castro     geography        mission      2
26       diverse         castro        latino        mission      2
21       diverse         castro       diverse        mission      4
31           fun         castro     community        mission      1
35           fun         castro    gentrified        mission      1
38           fun         castro        latino        mission      1
41           fun         castro       weather        mission      1
36           fun         castro        gritty        mission      2
37           fun         castro  institutions        mission      2
39           fun         castro          nice        mission      2
40           fun         castro       special        mission      2
30           fun         castro       chaotic        mission      3
29           fun         castro      antitask        mission      4
32           fun         castro       diverse        mission      7
33           fun         castro          food        mission      7
34           fun         castro           fun        mission     26
42           gay         castro       actions        mission      1
44           gay         castro       chaotic        mission      1
49           gay         castro           gay        mission      1
54           gay         castro     normative        mission      1
58           gay         castro         young        mission      1

## Save CSVs

In [8]:
df_fwd_castro_marina.to_csv("/Users/senko/Desktop/castro/analysis/prob_analysis/castro_marina_forward.csv", index=False)
df_bwd_castro_marina.to_csv("/Users/senko/Desktop/castro/analysis/prob_analysis/castro_marina_backward.csv", index=False)
df_fwd_castro_mission.to_csv("/Users/senko/Desktop/castro/analysis/prob_analysis/castro_mission_forward.csv", index=False)
df_bwd_castro_mission.to_csv("/Users/senko/Desktop/castro/analysis/prob_analysis/castro_mission_backward.csv", index=False)

# Single word clean analysis

## Straight

In [9]:
prob.single_word_prob(df_all, target_fieldsite="marina_res", 
                      target_word="straight", word_col= "clean_response2", w1_col = "category1",
                      target_r1_site="castro", target_r2_site="marina", 
                      count_filter=0)

prob.single_word_prob(df_all, target_fieldsite="marina_res", 
                      target_word="straight", word_col= "clean_response1", w1_col = "category2",
                      target_r1_site="marina", target_r2_site="castro", 
                      count_filter=0)

prob.single_word_prob(df_all, target_fieldsite="castro_res", 
                      target_word="straight", word_col= "clean_response2", w1_col = "category1",
                      target_r1_site="castro", target_r2_site="marina", 
                      count_filter=0)

prob.single_word_prob(df_all, target_fieldsite="castro_vis", 
                      target_word="straight", word_col= "clean_response2", w1_col = "category1",
                      target_r1_site="castro", target_r2_site="marina", 
                      count_filter=0)

Probability of straight in position clean_response2 for marina_res participants with response_site1=castro and response_site2=marina:
  category1 clean_response2  count  probability
0       fun        straight      1          1.0
Probability of straight in position clean_response1 for marina_res participants with response_site1=marina and response_site2=castro:
Empty DataFrame
Columns: [category2, clean_response1, count, probability]
Index: []
Probability of straight in position clean_response2 for castro_res participants with response_site1=castro and response_site2=marina:
  category1 clean_response2  count  probability
0       gay        straight      2          1.0
Probability of straight in position clean_response2 for castro_vis participants with response_site1=castro and response_site2=marina:
  category1 clean_response2  count  probability
0       gay        straight      6     0.857143
1      nice        straight      1     0.142857

## Latino

In [10]:
prob.single_word_prob(df_all, target_fieldsite="mission_res", 
                      target_word="latino", word_col= "clean_response2", w1_col = "category1",
                      target_r1_site="castro", target_r2_site="mission", 
                      count_filter=0)

prob.single_word_prob(df_all, target_fieldsite="mission_res", 
                      target_word="latino", word_col= "clean_response1", w1_col = "category2",
                      target_r1_site="mission", target_r2_site="castro", 
                      count_filter=0)

prob.single_word_prob(df_all, target_fieldsite="castro_res", 
                      target_word="latino", word_col= "clean_response2", w1_col = "category1",
                      target_r1_site="castro", target_r2_site="mission", 
                      count_filter=0)

prob.single_word_prob(df_all, target_fieldsite="castro_vis", 
                      target_word="latino", word_col= "clean_response2", w1_col = "category1",
                      target_r1_site="castro", target_r2_site="mission", 
                      count_filter=0)

Probability of latino in position clean_response2 for mission_res participants with response_site1=castro and response_site2=mission:
      category1 clean_response2  count  probability
0      antitask          latino      1     0.111111
1           gay          latino      4     0.444444
2     geography          latino      1     0.111111
3  institutions          latino      1     0.111111
4         other          latino      1     0.111111
5       special          latino      1     0.111111
Probability of latino in position clean_response1 for mission_res participants with response_site1=mission and response_site2=castro:
   category2 clean_response1  count  probability
0  community          latino      2          0.4
1        gay          latino      1          0.2
2      other          latino      2          0.4
Probability of latino in position clean_response2 for castro_res participants with response_site1=castro and response_site2=mission:
  category1 clean_response2  count  probability
0       gay          latino      5          1.0
Probability of latino in position clean_response2 for castro_vis participants with response_site1=castro and response_site2=mission:
  category1 clean_response2  count  probability
0       fun          latino      1         0.25
1       gay          latino      3         0.75